project_id = "wlmefliezatakbnkctbv"

[functions.roster]
verify_jwt = false

[functions.entity-data]
verify_jwt = false

[functions.entity-chat]
verify_jwt = false

[functions.interest-match]
verify_jwt = false

[functions.roster-search-chat]
verify_jwt = false